# Generated by Django 6.0.6 on 2026-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDetails',
            fields=[
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('battery_charge', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(default=0.0)),
                ('battery_output', models.FloatField(default=0.0)),
                ('battery_temperature', models.FloatField(blank=True, null=True)),
                ('solar_output', models.FloatField(blank=True, null=True)),
                ('electricityload_value', models.FloatField(blank=True, null=True)),
                ('water_usage', models.FloatField(blank=True, null=True)),
                ('gas_usage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sensor_details',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherPulled',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('min_temp', models.FloatField(blank=True, null=True)),
                ('max_temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather_pulled',
                'ordering': ['day'],
            },
        ),
    ]
