# Generated by Django 6.0.6 on 2026-07-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_misc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Misc',
        ),
    ]
