# Generated by Django 6.0.6 on 2026-07-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_misc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filter_value', models.IntegerField(default=0)),
                ('sort_value', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'misc',
            },
        ),
    ]
