# Generated by Django 6.0.6 on 2026-07-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_misc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
