# Generated by Django 6.0.6 on 2026-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_misc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
