# Generated by Django 6.0.6 on 2026-07-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_misc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misc',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
