# Generated by Django 6.0.6 on 2026-07-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_misc_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Misc',
        ),
    ]
