# Generated by Django 6.0.6 on 2026-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='misc',
            name='filter_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='misc',
            name='filter_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
