# Generated by Django 6.0.6 on 2026-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_misc_filter_range_misc_filter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misc',
            name='filter_range',
        ),
        migrations.AddField(
            model_name='misc',
            name='ran_End',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='misc',
            name='ran_Start',
            field=models.FloatField(default=0.0),
        ),
    ]
